#os: Visual Studio 2013 - GCE

#only_commits:
#  message: /build/

install:
- ps: .\fix-nunit.ps1

build:
  verbosity: minimal

before_build:
- nuget restore

test:
  categories:
    except:
    - A
    - B
